// build-brain.mjs — bundle THIS channel's brain from THIS channel's own source.
//
// The brain the add-on actually runs is `server/brain/voice-brain.bundle.js`, an
// esbuild bundle of `server/brain/src/`. Everything else in this tree is
// generated by brand-gen from the Dashie sources; the bundle deliberately is
// NOT, and the distinction is load-bearing:
//
//   brand-gen is a TEXT transform. Running it over a bundle would produce a
//   brain whose code no longer matched the source sitting beside it — and this
//   channel DROPS the product knowledge base, so a text-substituted bundle
//   would have gone on shipping Dashie's product documentation while
//   server/brain/src/ said it had been removed. Green gates, wrong brain.
//
// So the bundle is BUILT from this tree, not copied into it. Same reason
// `integration/` is vendored from its own generated repo rather than rewritten
// here: an artifact with its own producer should come from that producer.
//
// Usage:
//   node scripts/build-brain.mjs            build + write
//   node scripts/build-brain.mjs --check    build in memory and diff (no write)

import { createRequire } from 'node:module';
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const brainDir = path.join(repoRoot, 'chickadee', 'server', 'brain');
const entry = path.join(brainDir, 'src', 'voice-conversation', 'orchestrator.ts');
const outfile = path.join(brainDir, 'voice-brain.bundle.js');
// Required at boot by server/index.js — see the write below.
const metafile = path.join(brainDir, 'voice-brain.bundle.meta.json');

if (!existsSync(entry)) {
  console.error(`build-brain: no brain source at ${path.relative(repoRoot, entry)}.`);
  console.error('             Generate the channel first (brand-gen --table dashie-console).');
  process.exit(1);
}

// esbuild is not a dependency of this repo; borrow the one the generator's repo
// already installs. Stated rather than silently resolved: if this path is wrong
// the failure should name the reason.
const ESBUILD_HOST = path.join(process.env.HOME, 'projects', 'dashieapp_staging', 'kiosk-overlay', 'package.json');
if (!existsSync(ESBUILD_HOST)) {
  console.error('build-brain: esbuild not found. This script borrows the install at');
  console.error(`             ${ESBUILD_HOST}`);
  process.exit(1);
}
const esbuild = createRequire(ESBUILD_HOST)('esbuild');

// 🔴 THE STAMP IDENTIFIES THE SOURCE, NOT THE BUILD MOMENT.
//
// It used to be `git rev-parse HEAD` of THIS repo, which meant every rebuild
// after any commit rewrote the bundle and its sidecar with a new SHA — with zero
// code change. The tree was permanently dirty, and a genuine bundle change was
// indistinguishable from the churn.
//
// That is byte-for-byte the kiosk-overlay defect fixed on 2026-07-31, reborn
// here because I reached for the same convenient value. A build stamp answers
// "which SOURCE is this built from", and HEAD-at-build-time answers "when did I
// press the button" — which is not a property of the artifact at all.
//
// The channel's GENERATED stamp is the right answer: it names the upstream ref
// this whole tree came from, and it does not move unless the source does. So an
// identical source rebuilds to identical bytes, and a dirty bundle once again
// means a REAL change.
function sourceProvenance() {
  const gen = path.join(repoRoot, 'chickadee', 'GENERATED');
  if (existsSync(gen)) {
    const text = readFileSync(gen, 'utf8').trim();
    const m = text.match(/^Generated from (\S+) @ ([0-9a-f]{7,40})/);
    if (m) return { source: `${m[1]} @ ${m[2]}`, sha: m[2] };
  }
  // No usable stamp: hash the brain source itself. Deterministic, so it still
  // does not churn — and it degrades to something true rather than to HEAD,
  // which is the value that caused the problem.
  const files = [];
  const walkSrc = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const f = path.join(d, e.name);
      if (e.isDirectory()) walkSrc(f); else if (/\.(ts|js)$/.test(e.name)) files.push(f);
    }
  };
  try { walkSrc(path.join(brainDir, 'src')); } catch { /* handled below */ }
  const h = createHash('sha256');
  for (const f of files.sort()) h.update(readFileSync(f));
  return { source: 'content-hash (no GENERATED stamp)', sha: h.digest('hex').slice(0, 12) };
}
const { source: SOURCE_DESC, sha } = sourceProvenance();

const banner = `/* ============================================================
   AUTO-GENERATED — DO NOT EDIT BY HAND
   ------------------------------------------------------------
   The Chickadee voice brain, bundled for the Node add-on.
   Built from this channel's OWN server/brain/src/ — not copied, and not
   text-substituted from another brand's bundle. See scripts/build-brain.mjs
   for why that distinction matters.
   Built from: ${SOURCE_DESC}
   Regenerate:  node scripts/build-brain.mjs
   ============================================================ */`;

const buildOptions = {
  entryPoints: [entry],
  bundle: true,
  format: 'cjs',
  platform: 'node',
  target: 'node20',
  banner: { js: banner },
  footer: { js: `module.exports.BRAIN_SOURCE_SHA = ${JSON.stringify(sha)};` },
};

// The SHA moves on every commit, including ones that never touch the brain, so
// --check normalizes it out and compares the BODY. A gate that cries wolf weekly
// gets disabled, which is worse than no gate.
// Kept, but it should now be a NO-OP in practice: the stamp no longer moves
// unless the source does. If this normalisation ever starts mattering again,
// something has reintroduced a build-moment value.
const stripSha = (s) => s.replace(/Built from: [^\n]*/g, 'Built from: <source>')
  .replace(/BRAIN_SOURCE_SHA = "[0-9a-f]+"/g, 'BRAIN_SOURCE_SHA = "<sha>"');

if (CHECK) {
  const built = await esbuild.build({ ...buildOptions, write: false, logLevel: 'silent' });
  const fresh = built.outputFiles[0].text;
  if (!existsSync(outfile)) {
    console.error('❌ build-brain --check: no bundle on disk. The add-on has no brain to run.');
    console.error('   Run: node scripts/build-brain.mjs');
    process.exit(1);
  }
  // The sidecar is required at boot, so --check must assert it too. Without this
  // the check certified a brain that could not start — which is exactly what it
  // did, green, while the container was exiting(1).
  if (!existsSync(metafile)) {
    console.error('❌ build-brain --check: the bundle is present but its meta.json sidecar is NOT.');
    console.error('   server/index.js requires it at boot: the add-on installs, starts and dies.');
    console.error('   Run: node scripts/build-brain.mjs');
    process.exit(1);
  }
  if (stripSha(fresh) !== stripSha(readFileSync(outfile, 'utf8'))) {
    console.error('❌ build-brain --check: the committed bundle is NOT what this source builds.');
    console.error('   The add-on would run a brain that disagrees with server/brain/src/.');
    console.error('   Run: node scripts/build-brain.mjs   and commit the result.');
    process.exit(1);
  }
  console.log('✅ build-brain --check: the committed bundle matches this channel\'s source');
  process.exit(0);
}

mkdirSync(path.dirname(outfile), { recursive: true });
await esbuild.build({ ...buildOptions, outfile, logLevel: 'info' });

// 🔴 THE SIDECAR IS NOT OPTIONAL. server/index.js does
// `require('./brain/voice-brain.bundle.meta.json')` at boot, so a bundle without
// its twin is a container that exits(1) with "Cannot find module" — the add-on
// installs, starts, and dies.
//
// It shipped that way: the generator EXCLUDES both files (a built artifact is
// not its to write) and this script wrote only one of them, so the sidecar was
// excluded by one mechanism and never produced by the other. Neither was wrong
// alone; the gap was between them.
// Field NAMES unchanged: server/index.js reads `shortSha` for its startup log,
// and renaming it would be a second break to fix a first. Only the VALUE moves —
// from "this repo's HEAD when I built" to "the source this tree came from",
// which is what a reader of a build stamp actually wants to know.
writeFileSync(metafile, JSON.stringify({
  sha,
  shortSha: sha.slice(0, 9),
  source: SOURCE_DESC,
  builtFrom: 'chickadee/server/brain/src/voice-conversation/orchestrator.ts',
}, null, 2) + '\n');

console.log(`[build-brain] bundled Chickadee brain @ ${sha.slice(0, 9)} → ${path.relative(repoRoot, outfile)}`);
console.log(`[build-brain] wrote sidecar ${path.relative(repoRoot, metafile)}`);
