// build-brain.mjs — bundle THIS channel's brain from THIS channel's own source.
//
// The brain the add-on actually runs is `server/brain/voice-brain.bundle.js`, an
// esbuild bundle of `server/brain/src/`. Everything else in this tree is
// generated by brand-gen from the Dashie sources; the bundle deliberately is
// NOT, and the distinction is load-bearing:
//
//   brand-gen is a TEXT transform. Running it over a bundle would produce a
//   brain whose code no longer matched the source sitting beside it — and this
//   channel DROPS the product knowledge base, so a text-substituted bundle
//   would have gone on shipping Dashie's product documentation while
//   server/brain/src/ said it had been removed. Green gates, wrong brain.
//
// So the bundle is BUILT from this tree, not copied into it. Same reason
// `integration/` is vendored from its own generated repo rather than rewritten
// here: an artifact with its own producer should come from that producer.
//
// Usage:
//   node scripts/build-brain.mjs            build + write
//   node scripts/build-brain.mjs --check    build in memory and diff (no write)

import { createRequire } from 'node:module';
import { execSync } from 'node:child_process';
import { readFileSync, existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const brainDir = path.join(repoRoot, 'chickadee', 'server', 'brain');
const entry = path.join(brainDir, 'src', 'voice-conversation', 'orchestrator.ts');
const outfile = path.join(brainDir, 'voice-brain.bundle.js');

if (!existsSync(entry)) {
  console.error(`build-brain: no brain source at ${path.relative(repoRoot, entry)}.`);
  console.error('             Generate the channel first (brand-gen --table dashie-console).');
  process.exit(1);
}

// esbuild is not a dependency of this repo; borrow the one the generator's repo
// already installs. Stated rather than silently resolved: if this path is wrong
// the failure should name the reason.
const ESBUILD_HOST = path.join(process.env.HOME, 'projects', 'dashieapp_staging', 'kiosk-overlay', 'package.json');
if (!existsSync(ESBUILD_HOST)) {
  console.error('build-brain: esbuild not found. This script borrows the install at');
  console.error(`             ${ESBUILD_HOST}`);
  process.exit(1);
}
const esbuild = createRequire(ESBUILD_HOST)('esbuild');

const sha = execSync('git rev-parse HEAD', { cwd: repoRoot }).toString().trim();

const banner = `/* ============================================================
   AUTO-GENERATED — DO NOT EDIT BY HAND
   ------------------------------------------------------------
   The Chickadee voice brain, bundled for the Node add-on.
   Built from this channel's OWN server/brain/src/ — not copied, and not
   text-substituted from another brand's bundle. See scripts/build-brain.mjs
   for why that distinction matters.
   Source git SHA: ${sha}
   Regenerate:  node scripts/build-brain.mjs
   ============================================================ */`;

const buildOptions = {
  entryPoints: [entry],
  bundle: true,
  format: 'cjs',
  platform: 'node',
  target: 'node20',
  banner: { js: banner },
  footer: { js: `module.exports.BRAIN_SOURCE_SHA = ${JSON.stringify(sha)};` },
};

// The SHA moves on every commit, including ones that never touch the brain, so
// --check normalizes it out and compares the BODY. A gate that cries wolf weekly
// gets disabled, which is worse than no gate.
const stripSha = (s) => s.replace(/Source git SHA: [0-9a-f]{40}/g, 'Source git SHA: <sha>')
  .replace(/BRAIN_SOURCE_SHA = "[0-9a-f]{40}"/g, 'BRAIN_SOURCE_SHA = "<sha>"');

if (CHECK) {
  const built = await esbuild.build({ ...buildOptions, write: false, logLevel: 'silent' });
  const fresh = built.outputFiles[0].text;
  if (!existsSync(outfile)) {
    console.error('❌ build-brain --check: no bundle on disk. The add-on has no brain to run.');
    console.error('   Run: node scripts/build-brain.mjs');
    process.exit(1);
  }
  if (stripSha(fresh) !== stripSha(readFileSync(outfile, 'utf8'))) {
    console.error('❌ build-brain --check: the committed bundle is NOT what this source builds.');
    console.error('   The add-on would run a brain that disagrees with server/brain/src/.');
    console.error('   Run: node scripts/build-brain.mjs   and commit the result.');
    process.exit(1);
  }
  console.log('✅ build-brain --check: the committed bundle matches this channel\'s source');
  process.exit(0);
}

mkdirSync(path.dirname(outfile), { recursive: true });
await esbuild.build({ ...buildOptions, outfile, logLevel: 'info' });
console.log(`[build-brain] bundled Chickadee brain @ ${sha.slice(0, 9)} → ${path.relative(repoRoot, outfile)}`);
